version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - intrange
    - loggercheck
    - misspell
    - modernize
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    gocyclo:
      min-complexity: 15
    exhaustive:
      default-signifies-exhaustive: true
    nolintlint:
      require-specific: true
      require-explanation: true
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    wrapcheck:
      ignore-package-globs:
        - github.com/pg-es/pg-es-proxy/*
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: unused-parameter
        - name: var-declaration
        - name: var-naming

formatters:
  enable:
    - gofumpt
    - goimports

