version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - nolintlint
  settings:
    nolintlint:
      require-specific: true
      require-explanation: true
