[tools]
go = "1.27.0"
"go:golang.org/x/tools/gopls" = "0.23.0"
"go:github.com/cristian-sima/deadexports" = "0.0.0-20260627204954-f5eec8cbad01"
golangci-lint = "2.13.1"
prek = "0.3.8"
goreleaser = "2.16.0"

[task_config]
includes = ["mise/tasks"]
